language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t nikolamir/docker-react -f Dockerfile.dev .

 script:
 - docker run -e CI=true nikolamir/docker-react npm run test 